### ISSUE TITLE
Making it work?

### ISSUE THREAD

**Issue by nickdhillon100** [haydenshively/Cafe-Chi#1]
Hi Hayden, please can you help get it operating on my machine?

**Comment by mjsmorgan** [comment]
these links might help if you are installing on ubuntu:

https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one
https://classic.yarnpkg.com/en/docs/install/#debian-stable

following the yarn installation instructions run:

sudo apt-get install npm

yarn install works after that

**Comment by haydenshively** [comment]
@nickdhillon100 I'm going to close this issue for now, but if you need further instructions feel free to reopen
